import 'package:road_map/animated_tournament_bracket.dart';

class BracketData {
  // Tab 1: Upper Bracket Matches
  static const List<MatchModel> round1Tab1 = [
    MatchModel(
      id: 1,
      label: 'Match 1',
      table: 'Table 1',
      time: 'Sun 10:20 PM',
      player1: Player(name: 'David Alcaide Bermudez', flag: '🇪🇸'),
      player2: Player.walkOver,
      score1: 0,
      score2: 0,
    ),
    MatchModel(
      id: 2,
      label: 'Match 2',
      table: 'Table 1',
      time: 'Sat 10:18 PM',
      player1: Player(name: 'Billy Thorpe', flag: '🇺🇸', isCheckedIn: true),
      player2: Player(name: 'Skyler Woodward', flag: '🇺🇸', isCheckedIn: true),
      score1: 1,
      score2: 7,
      status: MatchStatus.inProgress,
    ),
    MatchModel(
      id: 3,
      label: 'Match 3',
      table: 'Table 1',
      time: 'Sat 06:43 PM',
      player1: Player(name: 'Kelly Fisher', flag: '🇬🇧'),
      player2: Player(name: 'Justin Sajich', flag: '🇦🇺'),
      score1: 3,
      score2: 7,
      status: MatchStatus.dispute,
    ),
    MatchModel(
      id: 4,
      label: 'Match 4',
      table: 'Table 1',
      time: 'Sun 08:42 PM',
      player1: Player.walkOver,
      player2: Player(name: 'Alex Kazakis', flag: '🇬🇷'),
      score1: 0,
      score2: 0,
    ),
    MatchModel(
      id: 5,
      label: 'Match 5',
      table: 'Table 1',
      time: 'Sun 08:42 PM',
      player1: Player(name: 'Naoyuki Oi', flag: '🇯🇵'),
      player2: Player.walkOver,
      score1: 0,
      score2: 0,
    ),
    MatchModel(
      id: 6,
      label: 'Match 6',
      table: 'Table 1',
      time: 'Sat 07:59 PM',
      player1: Player(name: 'Eklent Kaçi', flag: '🇦🇱'),
      player2: Player(name: 'Petri Makkonen', flag: '🇫🇮'),
      score1: 7,
      score2: 3,
    ),
    MatchModel(
      id: 7,
      label: 'Match 7',
      table: 'Table 1',
      time: 'Sun 12:11 PM',
      player1: Player(name: 'Niels Feijen', flag: '🇳🇱'),
      player2: Player(name: 'Jeffrey De Luna', flag: '🇵🇭'),
      score1: 7,
      score2: 3,
    ),
    MatchModel(
      id: 8,
      label: 'Match 8',
      table: 'Table 1',
      time: 'Sun 12:11 PM',
      player1: Player.walkOver,
      player2: Player(name: 'Jayson Shaw', flag: '🇬🇧'),
      score1: 0,
      score2: 0,
    ),
  ];

  static const List<MatchModel> round2Tab1 = [
    MatchModel(
      id: 17,
      label: 'Match 17',
      table: 'Table 1',
      time: 'Sun 10:20 PM',
      player1: Player(name: 'David Alcaide Bermudez', flag: '🇪🇸'),
      player2: Player(name: 'Skyler Woodward', flag: '🇺🇸'),
      score1: 3,
      score2: 7,
    ),
    MatchModel(
      id: 18,
      label: 'Match 18',
      table: 'Table 1',
      time: 'Mon 06:35 PM',
      player1: Player(name: 'Justin Sajich', flag: '🇦🇺'),
      player2: Player(name: 'Alex Kazakis', flag: '🇬🇷'),
      score1: 3,
      score2: 7,
    ),
    MatchModel(
      id: 19,
      label: 'Match 19',
      table: 'Table 1',
      time: 'Sun 08:42 PM',
      player1: Player(name: 'Naoyuki Oi', flag: '🇯🇵'),
      player2: Player(name: 'Eklent Kaçi', flag: '🇦🇱'),
      score1: 5,
      score2: 7,
    ),
    MatchModel(
      id: 20,
      label: 'Match 20',
      table: 'Table 1',
      time: 'Mon 03:49 PM',
      player1: Player(name: 'Niels Feijen', flag: '🇳🇱'),
      player2: Player(name: 'Jayson Shaw', flag: '🇬🇧'),
      score1: 7,
      score2: 6,
    ),
  ];

  static const List<MatchModel> round3Tab1 = [
    MatchModel(
      id: 25,
      label: 'Match 25',
      table: 'Table 1',
      time: 'Tue 03:42 PM',
      player1: Player(name: 'Skyler Woodward', flag: '🇺🇸'),
      player2: Player(name: 'Alex Kazakis', flag: '🇬🇷'),
      score1: 3,
      score2: 7,
    ),
    MatchModel(
      id: 26,
      label: 'Match 26',
      table: 'Table 1',
      time: 'Mon 09:06 PM',
      player1: Player(name: 'Eklent Kaçi', flag: '🇦🇱'),
      player2: Player(name: 'Niels Feijen', flag: '🇳🇱'),
      score1: 7,
      score2: 0,
    ),
  ];

  static const List<MatchModel> round4Tab1 = [
    MatchModel(
      id: 29,
      label: 'Match 29',
      table: 'Table 1',
      time: 'Tue 06:44 PM',
      player1: Player(name: 'Alex Kazakis', flag: '🇬🇷'),
      player2: Player(name: 'Eklent Kaçi', flag: '🇦🇱'),
      score1: 7,
      score2: 6,
    ),
  ];

  // Tab 2: Lower Bracket Matches
  static const List<MatchModel> round1Tab2 = [
    MatchModel(
      id: 9,
      label: 'Match 9',
      table: 'Table 1',
      time: 'Sun 02:28 PM',
      player1: Player(name: 'Fedor Gorst', flag: '🇷🇺'),
      player2: Player.walkOver,
      score1: 0,
      score2: 0,
    ),
    MatchModel(
      id: 10,
      label: 'Match 10',
      table: 'Table 1',
      time: 'Sun 06:57 PM',
      player1: Player(name: 'Shane Van Boening', flag: '🇺🇸'),
      player2: Player(name: 'Jakub Koniar', flag: '🇸🇰'),
      score1: 7,
      score2: 4,
    ),
    MatchModel(
      id: 11,
      label: 'Match 11',
      table: 'Table 1',
      time: 'Sun 01:16 PM',
      player1: Player(name: 'Mieszko Fortuński', flag: '🇵🇱'),
      player2: Player(name: 'Kristina Tkach', flag: '🇷🇺'),
      score1: 7,
      score2: 2,
    ),
    MatchModel(
      id: 12,
      label: 'Match 12',
      table: 'Table 1',
      time: 'Sun 01:16 PM',
      player1: Player.walkOver,
      player2: Player(name: 'Max Lechner', flag: '🇦🇹'),
      score1: 0,
      score2: 0,
    ),
    MatchModel(
      id: 13,
      label: 'Match 13',
      table: 'Table 1',
      time: 'Sun 04:11 PM',
      player1: Player(name: 'Joshua Filler', flag: '🇩🇪'),
      player2: Player.walkOver,
      score1: 0,
      score2: 0,
    ),
    MatchModel(
      id: 14,
      label: 'Match 14',
      table: 'Table 1',
      time: 'Sat 09:08 PM',
      player1: Player(name: 'Chris Melling', flag: '🇬🇧'),
      player2: Player(name: 'Sanjin Pehlivanovic', flag: '🇧🇦'),
      score1: 7,
      score2: 4,
    ),
    MatchModel(
      id: 15,
      label: 'Match 15',
      table: 'Table 1',
      time: 'Sun 02:28 PM',
      player1: Player(name: 'Denis Grabe', flag: '🇪🇪'),
      player2: Player(name: 'Roberto Gomez', flag: '🇵🇭'),
      score1: 7,
      score2: 6,
    ),
    MatchModel(
      id: 16,
      label: 'Match 16',
      table: 'Table 1',
      time: 'Sun 02:28 PM',
      player1: Player.walkOver,
      player2: Player(name: 'Albin Ouschan', flag: '🇦🇹'),
      score1: 0,
      score2: 0,
    ),
  ];

  static const List<MatchModel> round2Tab2 = [
    MatchModel(
      id: 21,
      label: 'Match 21',
      table: 'Table 1',
      time: 'Mon 07:54 PM',
      player1: Player(name: 'Fedor Gorst', flag: '🇷🇺'),
      player2: Player(name: 'Shane Van Boening', flag: '🇺🇸'),
      score1: 1,
      score2: 7,
    ),
    MatchModel(
      id: 22,
      label: 'Match 22',
      table: 'Table 1',
      time: 'Mon 12:59 PM',
      player1: Player(name: 'Mieszko Fortuński', flag: '🇵🇱'),
      player2: Player(name: 'Max Lechner', flag: '🇦🇹'),
      score1: 5,
      score2: 7,
    ),
    MatchModel(
      id: 23,
      label: 'Match 23',
      table: 'Table 1',
      time: 'Sun 04:11 PM',
      player1: Player(name: 'Joshua Filler', flag: '🇩🇪'),
      player2: Player(name: 'Chris Melling', flag: '🇬🇧'),
      score1: 7,
      score2: 5,
    ),
    MatchModel(
      id: 24,
      label: 'Match 24',
      table: 'Table 1',
      time: 'Mon 02:28 PM',
      player1: Player(name: 'Denis Grabe', flag: '🇪🇪'),
      player2: Player(name: 'Albin Ouschan', flag: '🇦🇹'),
      score1: 7,
      score2: 3,
    ),
  ];

  static const List<MatchModel> round3Tab2 = [
    MatchModel(
      id: 27,
      label: 'Match 27',
      table: 'Table 1',
      time: 'Tue 02:27 PM',
      player1: Player(name: 'Shane Van Boening', flag: '🇺🇸'),
      player2: Player(name: 'Max Lechner', flag: '🇦🇹'),
      score1: 7,
      score2: 4,
    ),
    MatchModel(
      id: 28,
      label: 'Match 28',
      table: 'Table 1',
      time: 'Tue 01:09 PM',
      player1: Player(name: 'Joshua Filler', flag: '🇩🇪'),
      player2: Player(name: 'Denis Grabe', flag: '🇪🇪'),
      score1: 7,
      score2: 5,
    ),
  ];

  static const List<MatchModel> round4Tab2 = [
    MatchModel(
      id: 30,
      label: 'Match 30',
      table: 'Table 1',
      time: 'Tue 08:41 PM',
      player1: Player(name: 'Shane Van Boening', flag: '🇺🇸'),
      player2: Player(name: 'Joshua Filler', flag: '🇩🇪'),
      score1: 7,
      score2: 6,
    ),
  ];

  // Grand Final Match 31
  static const MatchModel grandFinal = MatchModel(
    id: 31,
    label: 'Match 31',
    table: 'Table 1',
    time: 'Tue 10:14 PM',
    player1: Player(name: 'Alex Kazakis', flag: '🇬🇷'),
    player2: Player(name: 'Shane Van Boening', flag: '🇺🇸'),
    score1: 9,
    score2: 0,
  );
}
